---
name: "DateAddedAdvanced"
guid: "c31ce313-d3d3-4a93-ad6d-8b235a9c2078"
version: "3.0.1.0"
targetAbi: "10.11.2.0"
framework: "<template>"
overview: "Improved DateAdded handling"
description: >
  Allows fore more fine-grained control over DateAdded attributes for database entries
category: "General"
owner: "verybadsoldier"
artifacts:
- "Jellyfin.Plugin.DateAddedAdvanced.dll"
changelog: >
  changelog
