---
name: "DateAddedAdvanced"
guid: "daed5573-33f9-460d-9d4f-d05a049306bb"
version: "<template>"
targetAbi: "10.10.7.0"
framework: "<template>"
overview: "Improved DateAdded handling"
description: >
  Allows fore more fine-grained control over DateAdded attributes for database entries
category: "General"
owner: "verybadsoldier"
artifacts:
- "Jellyfin.Plugin.DateAddedAdvanced.dll"
changelog: >
  changelog
