---
name: "DateAddedAdvanced"
guid: "c31ce313-d3d3-4a93-ad6d-8b235a9c2078"
version: "<template>"
targetAbi: "12.0.0.0"
framework: "<template>"
overview: "Improved DateAdded handling"
description: >
  Allows fore more fine-grained control over DateAdded attributes for database entries
category: "General"
owner: "verybadsoldier"
imageUrl: "https://raw.githubusercontent.com/verybadsoldier/Jellyfin.Plugin.DateAddedAdvanced/main/logo.png"
artifacts:
- "Jellyfin.Plugin.DateAddedAdvanced.dll"
changelog: >
  changelog
